---
sudo: required
services:
  - docker
install:
  - ./.build.bash
script:
  - docker ps | grep -q wavefront-forwarder && echo "CONTAINER BUILT & RUNNING SUCCESSFULLY" || "CONTAINER NOT RUNNING"
after_success:
 - ./.publish.bash
