#!/bin/bash -ex

# VARIABLES
export PREFIX=${PREFIX:-""}
export SERVER=${SERVER:-"https://metrics.wavefront.com/api/"}
export HOSTNAME=${HOSTNAME:-`hostname`}
test ${TOKEN}

# CONFIGURE
/usr/local/bin/confd -onetime -backend env
